# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Gilmarxd'
tagline:             'github pages'
description:         'Sou estudante de Ciência da Computação, estou no terceiro período de oito, gosto de Computação Gráfica com OpenGL em C++, seja bem-vindo e aproveito os conteúdos. <br><a style="margin-left:auto; margin-right:auto;" href="https://twitter.com/Gilmar_CS" target="_blank">@Gilmar_CS</a>'
url:                 'https://gilmarxd.github.io/'
baseurl:             ''
paginate:            4
paginate_path: "/page-:num"

# About/contact
author:
  name:              Gilmar Custodio
  url:               https://twitter.com/Gilmar_CS
  email:             gilmar_custodio_@hotmail.com

github:
  repo: 'http://github.com/gilmarxd/gilmarxd.github.io'

plugins:
  - jekyll-feed
  - jekyll-paginate

# Custom vars
version:             0.0.1
