# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Gilmar C. Sales'
tagline:             'github pages'
description:         'Estudante de Ciência da Computação, atualmente no quinto período de oito, estuda Computação Gráfica com OpenGL puro em C++. <br><a style="margin-left:auto; margin-right:auto;" href="https://twitter.com/Gilmarxd0" target="_blank">@Gilmarxd0</a>'
url:                 'https://gilmarxd.github.io/'
baseurl:             ''
paginate:            4
paginate_path: "/page-:num"

# About/contact
author:
  name:              Gilmar Custodio
  url:               https://twitter.com/Gilmarxd0
  email:             gilmar_custodio_@hotmail.com

github:
  repo: 'http://github.com/gilmarxd/gilmarxd.github.io'

plugins:
  - jekyll-feed
  - jekyll-paginate

# Custom vars
version:             0.0.1
